[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "report-terminal-theme"
version = "0.1.0"
dependencies = ["Pygments>=2.14"]

[tool.setuptools]
py-modules = ["terminal_theme"]

[project.entry-points."pygments.styles"]
linuxterm = "terminal_theme:LinuxTerminalStyle"

[project.entry-points."pygments.lexers"]
linuxconsole = "terminal_theme:LinuxConsoleLexer"
